### ISSUE TITLE
Background traffic generated without altitude

### ISSUE THREAD

**Issue by joakimrydberg** [USEPE-SesarJU/bluesky#22]
This issue is related to #21 

Problem: 
All background traffic, when tested for valid segments, gets assigned segment `'N/A'` which in turn causes issues like crashing or dropping the flight plan.

Cause:
When randomly generated, the flight plans assigns an altitude of `None` to both origin and destination. This will always resolve to `False` when checked if inside a valid segment.

Current fix:
I have made a [change](https://github.com/USEPE-SesarJU/bluesky/blob/bded37a3a8d318925b3f27bebd3331e2d018a172/usepe/city_model/scenario_definition.py#L1258) which sets all background traffic at 55m. 

Is this a suitable fix? Should it be a range of altitudes instead?
Was there a specific reason for setting the altitude to `None`?

**Comment by mbaena-nommon** [comment]
Hi Joakim, I think that the best option is to choose origin and destination altitudes randomly between 0 and the maximum building height (92m I believe) in the same way as for latitude and longitude. 

The altitude was set to None because when searching for the closest node, it randomly selected a node in the different altitudes for that lat lon. After the changes made in the plugin these months, probably the way to create the drones has slightly changed and then, this no longer works.

I will make the changes and commit asap.

**Comment by mbaena-nommon** [comment]
Changes made in [56384fde70a0ce8ca9f08e1e02defbd43b732366](https://github.com/USEPE-SesarJU/bluesky/commit/56384fde70a0ce8ca9f08e1e02defbd43b732366)
and [fdcd5467a2ebfc1e2336fd825ce1e663185a7c70](https://github.com/USEPE-SesarJU/bluesky/commit/fdcd5467a2ebfc1e2336fd825ce1e663185a7c70) so the altitude randomly selected between 0 and the maximum building height set in segmentation rules.json file

**Comment by joakimrydberg** [comment]
Verified and works
Thank you
