### ISSUE TITLE
KeyError in usepe_plugin.py when regular drone traffic accesses nodes defined by premade scenarios

### ISSUE THREAD

**Issue by joakimrydberg** [USEPE-SesarJU/bluesky#33]
When premade scenarios defines waypoints these are added to the graph as belonging to the segment `priority` (which has no defined attributes). This makes them available to other drone traffic as well.
When `processFlightPlans()` attempts to validate flight plans of such drones, it will crash with a KeyError when trying to look up the segment's `speed_max` attribute.
I assume the same would happen in `reprocessFlightPlans()`.

Can we disallow the use of these `priority` nodes when traversing the graph?

Related:
This is somewhat similar to #21

**Comment by jbueno-nommon** [comment]
Do all these waypoints have some common pattern in their name? When we search for the nearest node we can apply some filter. For example we filter the corridor nodes, so a drone cannot depart from a corridor. This is done with the following code in the `nearestNode3d()` function (all corridor names start with 'COR'):

`nodes = list( G.nodes )`
        `filtered_latlon = list( filter( lambda node: str( node )[:3] != 'COR', nodes ) )`

We can do the same with your priority nodes, and since they are not connected with the rest of the graph other drones will not use them.

**Comment by joakimrydberg** [comment]
The waypoints do not have any commonality across the scenarios, although we could change that.

However, as all these nodes are assigned the `priority` segment with your recent addition in `calcWptDict()`, and I don't think any other nodes have this segment, can't that be the filter?
Something like this maybe:

`nodes = G.nodes`
`filtered_latlon = list(filter(lambda node: nodes[node]['segment'] != 'priority', nodes))`

**Comment by jbueno-nommon** [comment]
I think so. Could you try that change and see if it works on your use case?
